# coding: utf-8

"""
    Impresso Public API

    Impresso Public API Documentation

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from impresso.api_client.models.auth_request_schema import AuthRequestSchema

class TestAuthRequestSchema(unittest.TestCase):
    """AuthRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthRequestSchema:
        """Test AuthRequestSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthRequestSchema`
        """
        model = AuthRequestSchema()
        if include_optional:
            return AuthRequestSchema(
                strategy = 'local',
                email = '',
                password = ''
            )
        else:
            return AuthRequestSchema(
                strategy = 'local',
                email = '',
                password = '',
        )
        """

    def testAuthRequestSchema(self):
        """Test AuthRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
