# coding: utf-8

"""
    Impresso Public API

    Impresso Public API Documentation

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from impresso.api_client.models.search_get_filters_parameter_inner_q import SearchGetFiltersParameterInnerQ

class TestSearchGetFiltersParameterInnerQ(unittest.TestCase):
    """SearchGetFiltersParameterInnerQ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchGetFiltersParameterInnerQ:
        """Test SearchGetFiltersParameterInnerQ
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchGetFiltersParameterInnerQ`
        """
        model = SearchGetFiltersParameterInnerQ()
        if include_optional:
            return SearchGetFiltersParameterInnerQ(
            )
        else:
            return SearchGetFiltersParameterInnerQ(
        )
        """

    def testSearchGetFiltersParameterInnerQ(self):
        """Test SearchGetFiltersParameterInnerQ"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
