# coding: utf-8

"""
    Impresso Public API

    Impresso Public API Documentation

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from impresso.api_client.api.articles_api import ArticlesApi


class TestArticlesApi(unittest.TestCase):
    """ArticlesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArticlesApi()

    def tearDown(self) -> None:
        pass

    def test_articles_get(self) -> None:
        """Test case for articles_get

        
        """
        pass

    def test_articles_id_get(self) -> None:
        """Test case for articles_id_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
