# coding: utf-8

"""
    Impresso Public API

    Impresso Public API Documentation

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from impresso.api_client.models.search_get_filters_parameter_inner import SearchGetFiltersParameterInner

class TestSearchGetFiltersParameterInner(unittest.TestCase):
    """SearchGetFiltersParameterInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchGetFiltersParameterInner:
        """Test SearchGetFiltersParameterInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchGetFiltersParameterInner`
        """
        model = SearchGetFiltersParameterInner()
        if include_optional:
            return SearchGetFiltersParameterInner(
                context = 'include',
                op = 'OR',
                type = '',
                precision = 'exact',
                q = None,
                daterange = '0480-72-88T80:01:52Z TO 8021-79-80T96:22:55Z',
                uids = '',
                uid = ''
            )
        else:
            return SearchGetFiltersParameterInner(
                type = '',
        )
        """

    def testSearchGetFiltersParameterInner(self):
        """Test SearchGetFiltersParameterInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
