# coding: utf-8

"""
    Impresso Public API

    Impresso Public API Documentation

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from impresso.api_client.models.page import Page

class TestPage(unittest.TestCase):
    """Page unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Page:
        """Test Page
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Page`
        """
        model = Page()
        if include_optional:
            return Page(
                uid = '',
                num = 56,
                issue_uid = '',
                newspaper_uid = '',
                iiif = '',
                iiif_thumbnail = '',
                access_rights = '',
                labels = [
                    ''
                    ],
                has_coords = True,
                has_errors = True,
                regions = [
                    None
                    ],
                obfuscated = True,
                iiif_fragment = ''
            )
        else:
            return Page(
                uid = '',
                num = 56,
                issue_uid = '',
                newspaper_uid = '',
                iiif_thumbnail = '',
                access_rights = '',
                labels = [
                    ''
                    ],
                has_coords = True,
                has_errors = True,
                regions = [
                    None
                    ],
        )
        """

    def testPage(self):
        """Test Page"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
