# coding: utf-8

"""
    Impresso Public API

    Impresso Public API Documentation

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from impresso.api_client.models.articles_get_filters_parameter import ArticlesGetFiltersParameter

class TestArticlesGetFiltersParameter(unittest.TestCase):
    """ArticlesGetFiltersParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArticlesGetFiltersParameter:
        """Test ArticlesGetFiltersParameter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArticlesGetFiltersParameter`
        """
        model = ArticlesGetFiltersParameter()
        if include_optional:
            return ArticlesGetFiltersParameter(
                type = 'uid',
                q = 'İ'
            )
        else:
            return ArticlesGetFiltersParameter(
                type = 'uid',
        )
        """

    def testArticlesGetFiltersParameter(self):
        """Test ArticlesGetFiltersParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
