# coding: utf-8

"""
    Impresso Public API

    Impresso Public API Documentation

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from impresso.api_client.models.auth_response_schema import AuthResponseSchema

class TestAuthResponseSchema(unittest.TestCase):
    """AuthResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthResponseSchema:
        """Test AuthResponseSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthResponseSchema`
        """
        model = AuthResponseSchema()
        if include_optional:
            return AuthResponseSchema(
                access_token = '',
                authentication = impresso.api_client.models.auth_response_schema_authentication.authResponseSchema_authentication(
                    strategy = '', 
                    payload = impresso.api_client.models.payload.payload(), ),
                user = impresso.api_client.models.user.User(
                    id = 56, 
                    username = '', 
                    firstname = '', 
                    lastname = '', 
                    is_staff = True, 
                    is_active = True, 
                    is_superuser = True, 
                    uid = '', )
            )
        else:
            return AuthResponseSchema(
                access_token = '',
                authentication = impresso.api_client.models.auth_response_schema_authentication.authResponseSchema_authentication(
                    strategy = '', 
                    payload = impresso.api_client.models.payload.payload(), ),
                user = impresso.api_client.models.user.User(
                    id = 56, 
                    username = '', 
                    firstname = '', 
                    lastname = '', 
                    is_staff = True, 
                    is_active = True, 
                    is_superuser = True, 
                    uid = '', ),
        )
        """

    def testAuthResponseSchema(self):
        """Test AuthResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
